services:
  backend:
    image: momo-store-backend:local
    build:
      context: ./backend
    ports:
      - "8081:8081"
  frontend:
    image: momo-store-frontend:local
    build:
      context: ./frontend
    ports:
      - "80:8080"

