services:
  backend:
    image: momo-store-backend
    build:
      context: ./backend
    ports:
      - "8081:8081"
  frontend:
    image: momo-store-frontend
    build:
      context: ./frontend
    ports:
      - "80:8080"
